apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-bindu08o
  labels:
    app: chatbot-bindu08o
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-bindu08o
  template:
    metadata:
      labels:
        app: chatbot-bindu08o
    spec:
      containers:
      - name: chatbot-bindu08o
        image: replace
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-bindu08o-service
spec:
  type: LoadBalancer
  selector:
    app: chatbot-bindu08o
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP